employees=[{"eid":1,"ename":"Carey","gender":"Female"},
{"eid":2,"ename":"Rickard","gender":"Bigender"},
{"eid":3,"ename":"Ellissa","gender":"Female"},
{"eid":4,"ename":"Mariette","gender":"Female"},
{"eid":5,"ename":"Coreen","gender":"Female"},
{"eid":6,"ename":"Adore","gender":"Female"},
{"eid":7,"ename":"Colleen","gender":"Female"},
{"eid":8,"ename":"Jami","gender":"Female"},
{"eid":9,"ename":"Osbert","gender":"Genderqueer"},
{"eid":10,"ename":"Erroll","gender":"Male"},
{"eid":11,"ename":"Brandtr","gender":"Male"},
{"eid":12,"ename":"Ingram","gender":"Male"},
{"eid":13,"ename":"Patin","gender":"Male"},
{"eid":14,"ename":"Ruddy","gender":"Genderqueer"},
{"eid":15,"ename":"Lianna","gender":"Female"},
{"eid":16,"ename":"Eadie","gender":"Polygender"},
{"eid":17,"ename":"Avigdor","gender":"Male"},
{"eid":18,"ename":"Wade","gender":"Male"},
{"eid":19,"ename":"Mel","gender":"Agender"},
{"eid":20,"ename":"Thayne","gender":"Male"},
{"eid":21,"ename":"Arty","gender":"Male"},
{"eid":22,"ename":"Cos","gender":"Male"},
{"eid":23,"ename":"Glennie","gender":"Female"},
{"eid":24,"ename":"Linus","gender":"Male"},
{"eid":25,"ename":"Che","gender":"Bigender"},
{"eid":26,"ename":"Ashlin","gender":"Polygender"},
{"eid":27,"ename":"Minda","gender":"Female"},
{"eid":28,"ename":"Didi","gender":"Female"},
{"eid":29,"ename":"Pip","gender":"Male"},
{"eid":30,"ename":"Falito","gender":"Male"},
{"eid":31,"ename":"Nerty","gender":"Genderfluid"},
{"eid":32,"ename":"Eydie","gender":"Female"},
{"eid":33,"ename":"Kimmy","gender":"Non-binary"},
{"eid":34,"ename":"Fanni","gender":"Female"},
{"eid":35,"ename":"Hilliard","gender":"Male"},
{"eid":36,"ename":"Aurora","gender":"Female"},
{"eid":37,"ename":"Veda","gender":"Female"},
{"eid":38,"ename":"Conny","gender":"Male"},
{"eid":39,"ename":"Marnia","gender":"Female"},
{"eid":40,"ename":"Lisha","gender":"Female"},
{"eid":41,"ename":"Jamima","gender":"Female"},
{"eid":42,"ename":"Beatrisa","gender":"Female"},
{"eid":43,"ename":"Roobbie","gender":"Genderfluid"},
{"eid":44,"ename":"Sigismondo","gender":"Male"},
{"eid":45,"ename":"Jud","gender":"Male"},
{"eid":46,"ename":"Vi","gender":"Female"},
{"eid":47,"ename":"Zabrina","gender":"Female"},
{"eid":48,"ename":"Millie","gender":"Female"},
{"eid":49,"ename":"Oona","gender":"Female"},
{"eid":50,"ename":"Tallie","gender":"Male"},
{"eid":51,"ename":"Maurits","gender":"Male"},
{"eid":52,"ename":"Anabella","gender":"Female"},
{"eid":53,"ename":"Kimberlee","gender":"Female"},
{"eid":54,"ename":"Delinda","gender":"Female"},
{"eid":55,"ename":"Town","gender":"Male"},
{"eid":56,"ename":"Joannes","gender":"Female"},
{"eid":57,"ename":"Dulcie","gender":"Female"},
{"eid":58,"ename":"Janos","gender":"Male"},
{"eid":59,"ename":"Benn","gender":"Male"},
{"eid":60,"ename":"Nikolos","gender":"Male"},
{"eid":61,"ename":"Manuel","gender":"Male"},
{"eid":62,"ename":"Ase","gender":"Male"},
{"eid":63,"ename":"Sandy","gender":"Female"},
{"eid":64,"ename":"Jaymee","gender":"Female"},
{"eid":65,"ename":"Elisabetta","gender":"Female"},
{"eid":66,"ename":"Donall","gender":"Male"},
{"eid":67,"ename":"Lars","gender":"Male"},
{"eid":68,"ename":"Hailey","gender":"Male"},
{"eid":69,"ename":"Murray","gender":"Male"},
{"eid":70,"ename":"Dominique","gender":"Female"},
{"eid":71,"ename":"Kizzie","gender":"Female"},
{"eid":72,"ename":"Bary","gender":"Male"},
{"eid":73,"ename":"Sigismundo","gender":"Male"},
{"eid":74,"ename":"Pip","gender":"Male"},
{"eid":75,"ename":"Deena","gender":"Bigender"},
{"eid":76,"ename":"Norrie","gender":"Male"},
{"eid":77,"ename":"Coriss","gender":"Female"},
{"eid":78,"ename":"Eddi","gender":"Non-binary"},
{"eid":79,"ename":"Sophia","gender":"Female"},
{"eid":80,"ename":"Evvie","gender":"Female"},
{"eid":81,"ename":"Cynthea","gender":"Female"},
{"eid":82,"ename":"Sam","gender":"Female"},
{"eid":83,"ename":"Lynne","gender":"Female"},
{"eid":84,"ename":"Harlie","gender":"Female"},
{"eid":85,"ename":"Kari","gender":"Female"},
{"eid":86,"ename":"Elissa","gender":"Female"},
{"eid":87,"ename":"Helli","gender":"Female"},
{"eid":88,"ename":"Paige","gender":"Genderfluid"},
{"eid":89,"ename":"Maximo","gender":"Male"},
{"eid":90,"ename":"Roch","gender":"Female"},
{"eid":91,"ename":"Farley","gender":"Male"},
{"eid":92,"ename":"Maurice","gender":"Male"},
{"eid":93,"ename":"Kristi","gender":"Polygender"},
{"eid":94,"ename":"Sisile","gender":"Female"},
{"eid":95,"ename":"Lance","gender":"Male"},
{"eid":96,"ename":"Cynthy","gender":"Female"},
{"eid":97,"ename":"Lezlie","gender":"Non-binary"},
{"eid":98,"ename":"Harmon","gender":"Male"},
{"eid":99,"ename":"Erma","gender":"Female"},
{"eid":100,"ename":"Elisabet","gender":"Female"}]
for employee  in employees:
    print("employee name", employee['ename'])
for employee in employees:
    if employee['gender']=='Male':
        print("Male employee",employee['ename'])

for emp in employees:
    if emp["gender"]=="female":
        print("female employees",emp["ename"])
male_emp=0
for emp in employees:
    if emp["gender"]=="Male":
        male_emp+=1
print("total male employees are:",male_emp)        